# Generated by Django 3.2.5 on 2021-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
