# Generated by Django 3.2.5 on 2021-07-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0008_auto_20210726_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hood_name',
            new_name='neighbourhood',
        ),
    ]
