# Generated by Django 3.2.5 on 2021-07-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0013_alter_post_neighbourhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='business',
            name='hood_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaa.neighbourhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='hood_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaa.neighbourhood'),
            preserve_default=False,
        ),
    ]
