# Generated by Django 3.2.5 on 2021-07-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0015_alter_post_hood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hood_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaa.neighbourhood'),
        ),
    ]
